"""create initial tables

Revision ID: a0a46060c2e7
Revises: 
Create Date: 2026-04-02 23:53:52.206213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'a0a46060c2e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=False),
    sa.Column('account_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_github_installation_id'), 'installation', ['github_installation_id'], unique=True)
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repository_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_github_repo_id'), 'repository', ['github_repo_id'], unique=True)
    op.create_index(op.f('ix_repository_installation_id'), 'repository', ['installation_id'], unique=False)
    op.create_table('repositorysettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('schedule_cron', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('network_enabled', sa.Boolean(), nullable=False),
    sa.Column('sandbox_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('target_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositorysettings_repository_id'), 'repositorysettings', ['repository_id'], unique=True)
    op.create_table('validationrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commit_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issue_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validationrun_repository_id'), 'validationrun', ['repository_id'], unique=False)
    op.create_table('validationstep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stderr_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validationrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validationstep_validation_run_id'), 'validationstep', ['validation_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validationstep_validation_run_id'), table_name='validationstep')
    op.drop_table('validationstep')
    op.drop_index(op.f('ix_validationrun_repository_id'), table_name='validationrun')
    op.drop_table('validationrun')
    op.drop_index(op.f('ix_repositorysettings_repository_id'), table_name='repositorysettings')
    op.drop_table('repositorysettings')
    op.drop_index(op.f('ix_repository_installation_id'), table_name='repository')
    op.drop_index(op.f('ix_repository_github_repo_id'), table_name='repository')
    op.drop_table('repository')
    op.drop_index(op.f('ix_installation_github_installation_id'), table_name='installation')
    op.drop_table('installation')
    # ### end Alembic commands ###
